- block:
    - name: check if instance exists
      shell: >
        . ~/overcloudrc_v3_hailstorm &&
        OS_TENANT_NAME={{ osp_tenant }}
        OS_PROJECT_NAME={{ osp_tenant }}
        OS_PASSWORD={{ root_password }}
        openstack server list -f json --name {{ inventory_hostname_short }}
      register: instance_data
      failed_when: instance_data.stdout == ""
      changed_when: false

    - name: terminate image
      shell: >
        . ~/overcloudrc_v3_hailstorm &&
        OS_TENANT_NAME={{ osp_tenant }}
        OS_PROJECT_NAME={{ osp_tenant }}
        OS_PASSWORD={{ root_password }}
        openstack server delete
        {{ inventory_hostname_short }}
      when: instance_data.stdout | from_json | length != 0

  become: yes
  become_user: "{{ hostvars['rhosp-director'].rhosp_stack_user }}"
  delegate_to: rhosp-director
